[[main]]
  name = "Selected Publications"
  url = "selected"
  weight = 20

[[main]]
  name = "Research"
  url = "research"
  weight = 30

[[main]]
  name = "Teaching"
  url = "teaching"
  weight = 40

[[main]]
  name = "Science Management"
  url = "management"
  weight = 50

[[main]]
  name = "Papers, Talks, CV"
  url = "papers"
  weight = 60
